/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaRouteImport } from './routes/qa'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as ReconciliationHistoryRouteImport } from './routes/reconciliation.history'
import { Route as ReconciliationHistoryRunIdRouteImport } from './routes/reconciliation.history.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationHistoryRoute = ReconciliationHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ReconciliationRoute,
} as any)
const ReconciliationHistoryRunIdRoute =
  ReconciliationHistoryRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => ReconciliationHistoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/qa': typeof QaRoute
  '/reconciliation': typeof ReconciliationRouteWithChildren
  '/reconciliation/history': typeof ReconciliationHistoryRouteWithChildren
  '/reconciliation/history/$runId': typeof ReconciliationHistoryRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/qa': typeof QaRoute
  '/reconciliation': typeof ReconciliationRouteWithChildren
  '/reconciliation/history': typeof ReconciliationHistoryRouteWithChildren
  '/reconciliation/history/$runId': typeof ReconciliationHistoryRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/qa': typeof QaRoute
  '/reconciliation': typeof ReconciliationRouteWithChildren
  '/reconciliation/history': typeof ReconciliationHistoryRouteWithChildren
  '/reconciliation/history/$runId': typeof ReconciliationHistoryRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/qa'
    | '/reconciliation'
    | '/reconciliation/history'
    | '/reconciliation/history/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/qa'
    | '/reconciliation'
    | '/reconciliation/history'
    | '/reconciliation/history/$runId'
  id:
    | '__root__'
    | '/'
    | '/qa'
    | '/reconciliation'
    | '/reconciliation/history'
    | '/reconciliation/history/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QaRoute: typeof QaRoute
  ReconciliationRoute: typeof ReconciliationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation/history': {
      id: '/reconciliation/history'
      path: '/history'
      fullPath: '/reconciliation/history'
      preLoaderRoute: typeof ReconciliationHistoryRouteImport
      parentRoute: typeof ReconciliationRoute
    }
    '/reconciliation/history/$runId': {
      id: '/reconciliation/history/$runId'
      path: '/$runId'
      fullPath: '/reconciliation/history/$runId'
      preLoaderRoute: typeof ReconciliationHistoryRunIdRouteImport
      parentRoute: typeof ReconciliationHistoryRoute
    }
  }
}

interface ReconciliationHistoryRouteChildren {
  ReconciliationHistoryRunIdRoute: typeof ReconciliationHistoryRunIdRoute
}

const ReconciliationHistoryRouteChildren: ReconciliationHistoryRouteChildren = {
  ReconciliationHistoryRunIdRoute: ReconciliationHistoryRunIdRoute,
}

const ReconciliationHistoryRouteWithChildren =
  ReconciliationHistoryRoute._addFileChildren(
    ReconciliationHistoryRouteChildren,
  )

interface ReconciliationRouteChildren {
  ReconciliationHistoryRoute: typeof ReconciliationHistoryRouteWithChildren
}

const ReconciliationRouteChildren: ReconciliationRouteChildren = {
  ReconciliationHistoryRoute: ReconciliationHistoryRouteWithChildren,
}

const ReconciliationRouteWithChildren = ReconciliationRoute._addFileChildren(
  ReconciliationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QaRoute: QaRoute,
  ReconciliationRoute: ReconciliationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
