import { Link, createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";

import { Header } from "@/components/site/Header";
import { WorkspaceBackground } from "@/components/site/BackgroundLayer";
import { getHistoricalRun, recheckHistoricalRun, type HistoricalRun } from "@/lib/financeApi";

export const Route = createFileRoute("/reconciliation/history/$runId")({ component: HistoricalRunPage });

function HistoricalRunPage() {
  const { runId } = Route.useParams();
  const [data, setData] = useState<HistoricalRun | null>(null);
  const [filter, setFilter] = useState("ALL");
  const [error, setError] = useState("");
  const [selected, setSelected] = useState<HistoricalRun["results"][number] | null>(null);
  useEffect(() => { void getHistoricalRun(runId).then((response) => setData(response.data)).catch((reason) => setError(reason instanceof Error ? reason.message : String(reason))); }, [runId]);
  if (error) return <div className="min-h-screen bg-background p-20 text-error"><h1 className="text-3xl text-primary">Historical Run</h1><p className="mt-4">{error}</p></div>;
  if (!data) return <div className="min-h-screen bg-background p-20 text-on-surface-variant"><h1 className="text-3xl text-primary">Historical Run</h1><p className="mt-4">Loading historical run...</p></div>;
  const visible = data.results.filter((item) => filter === "ALL" || (filter === "EXCEPTIONS" ? Boolean(item.warnings?.length) : item.matchType === filter));
  const recheck = async () => { try { const response = await recheckHistoricalRun(runId); window.location.href = `/reconciliation/history/${response.data.runId}`; } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } };
  return <div className="relative min-h-screen bg-background text-on-surface"><WorkspaceBackground opacity={0.28} /><Header sections={false} active="reconciliation" /><main className="relative z-10 max-w-6xl mx-auto px-margin-mobile md:px-margin-desktop py-32"><div className="flex flex-wrap items-end justify-between gap-4 mb-8"><div><Link to="/reconciliation/history" className="text-secondary hover:underline">← History</Link><h1 className="font-display-lg-mobile md:font-display-lg text-primary mt-4">Run v{data.run.version}</h1><p className="text-on-surface-variant">{data.run.runId} · {new Date(data.run.createdAt).toLocaleString()}</p></div><button type="button" onClick={() => void recheck()} className="bg-secondary text-on-secondary px-5 py-3 rounded-button">Recheck structured data</button></div>
    <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-5">{[["Invoices", data.summary.totalInvoices], ["Auto matched", data.summary.autoMatched], ["Review", data.summary.manualReview], ["Unmatched", data.summary.unmatched], ["Avg confidence", `${data.run.averageConfidence.toFixed(1)}%`]].map(([label, value]) => <div key={String(label)} className="glass-panel-solid rounded-xl p-4"><p className="text-xs uppercase text-on-surface-variant">{label}</p><p className="text-xl text-primary mt-2">{String(value)}</p></div>)}</div>
    <div className="glass-panel-solid rounded-2xl p-6 mb-5"><p className="text-sm text-on-surface-variant">Match rate {data.run.matchRate.toFixed(1)}% · Processing {data.run.processingTimeMs ?? "-"} ms</p><p className="text-sm text-on-surface-variant mt-2">Weights: {Object.entries(data.weights).map(([key, value]) => `${key} ${value}%`).join(" · ")} · Thresholds: auto {data.thresholds.auto ?? "-"}%, review {data.thresholds.review ?? "-"}%</p></div>
    <div className="flex flex-wrap gap-2 mb-5">{["ALL", "AUTO_MATCH", "MANUAL_REVIEW", "UNMATCHED", "EXCEPTIONS"].map((value) => <button key={value} type="button" onClick={() => setFilter(value)} className={`px-3 py-2 rounded-full border text-xs ${filter === value ? "bg-secondary text-on-secondary" : "border-outline-variant text-on-surface-variant"}`}>{value.replaceAll("_", " ")}</button>)}</div>
    <div className="glass-panel-solid rounded-2xl p-6 overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b border-outline-variant/50 text-sm text-on-surface-variant"><th className="pb-3">Invoice</th><th className="pb-3">Customer</th><th className="pb-3">Candidate</th><th className="pb-3">Confidence</th><th className="pb-3">Scores</th><th className="pb-3">Status</th><th className="pb-3">Reason</th></tr></thead><tbody>{visible.map((item) => <tr key={item.matchId} className="border-b border-outline-variant/20"><td className="py-4 font-semibold"><button type="button" onClick={() => setSelected(item)} className="text-secondary hover:underline">{item.invoice.invoiceNumber || item.invoiceId || "-"}</button></td><td className="py-4">{String(item.invoice.customerName || "-")}</td><td className="py-4">{item.transaction?.transactionId || item.bestCandidate?.transactionId || "None"}</td><td className="py-4">{item.confidence}%</td><td className="py-4 text-xs">{item.scores ? `Amt ${item.scores.amount} · Ref ${item.scores.reference} · Name ${item.scores.name} · Sem ${item.scores.semantic} · Date ${item.scores.date}` : "-"}</td><td className="py-4">{item.matchType.replaceAll("_", " ")}</td><td className="py-4 text-sm text-on-surface-variant">{item.reason?.summary || "-"}</td></tr>)}</tbody></table></div>
    {selected ? <div className="glass-panel-solid rounded-2xl p-6 mt-5"><div className="flex justify-between gap-4"><h2 className="font-headline-md text-primary">Invoice Details: {selected.invoice.invoiceNumber || selected.invoiceId}</h2><button type="button" onClick={() => setSelected(null)} className="text-secondary">Close</button></div><div className="grid md:grid-cols-2 gap-4 text-sm mt-5"><div><p>Customer: {String(selected.invoice.customerName || "-")}</p><p>Amount: {String(selected.invoice.amount ?? "-")}</p><p>Invoice date: {String(selected.invoice.invoiceDate || "-")}</p><p>Status: {selected.matchType.replaceAll("_", " ")}</p><p>Confidence: {selected.confidence}%</p></div><div><p>Selected transaction: {selected.transaction?.transactionId || "None"}</p><p>Best candidate: {selected.bestCandidate?.transactionId || "None"}</p><p>Candidate amount: {String(selected.bestCandidate?.amount ?? selected.transaction?.amount ?? "-")}</p><p>Reason: {selected.reason?.summary || "-"}</p></div></div>{selected.scores ? <p className="text-sm text-on-surface-variant mt-5">Scores: Amount {selected.scores.amount}, Reference {selected.scores.reference}, Name {selected.scores.name}, Semantic {selected.scores.semantic}, Date {selected.scores.date}</p> : null}{selected.warnings?.length ? <div className="mt-5">{selected.warnings.map((warning, index) => <p key={`${warning.type}-${index}`} className="text-sm text-error">{warning.type}: {warning.severity || "MEDIUM"}</p>)}</div> : null}</div> : null}
    <div className="glass-panel-solid rounded-2xl p-6 mt-5"><h2 className="font-headline-md text-primary mb-4">Exceptions</h2>{data.exceptions.length ? data.exceptions.map((item) => <div key={item.exceptionId} className="border-b border-outline-variant/20 py-3"><strong>{item.type}</strong> <span className="text-xs uppercase text-on-surface-variant">{item.severity}</span><p className="text-sm text-on-surface-variant mt-1">{item.invoiceId || "-"} · {item.description}</p></div>) : <p className="text-on-surface-variant">No exceptions.</p>}</div>
  </main></div>;
}
